name: Checkout
run-name: ${{ github.actor }} checking out the repository 🚀
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List files in the repository
        run: ls -R ${{ github.workspace}}
